using System;
using System.Collections.Generic;
using System.Linq;
using Kezyma.WholeHistoryRating;

namespace MscTournamentRatings
{
    class Program
    {
        static void Main(string[] args)
        {
            Dictionary<string, int> players = new Dictionary<string, int>();
            players.Add("TkMoreira", 1);
            players.Add("Christopher", 2);
            players.Add("BKXO", 3);
            players.Add("BigRig", 4);
            players.Add("J0k3r", 5);
            players.Add("CDH", 6);
            players.Add("Gold Nobody", 7);
            players.Add("T-boy", 8);
            players.Add("einBirnenbaum", 9);
            players.Add("Atto", 10);
            players.Add("Rocci", 11);
            players.Add("Yoyo", 13);
            players.Add("[CELTICS]", 14);
            players.Add("FB-Productions", 15);
            players.Add("ImSpiker", 16);
            players.Add("Terrestrial_X", 17);
            players.Add("Giant", 18);
            players.Add("Calvin", 19);
            players.Add("Jucarman", 20);
            players.Add("Kaz", 21);
            players.Add("Timely Yor", 22);
            players.Add("sigibua", 23);
            players.Add("Luso", 24);
            players.Add("Hi_Am_Disturbia", 25);
            players.Add("DemonMK", 26);
            players.Add("Ajmo1025", 27);
            players.Add("Jimboom", 28);

            var config = new Config(100);
            var whr = new WholeHistoryRating(config);

            whr.CreateGame(players["TkMoreira"], players["Gold Nobody"], WHResult.Player1Win, 3); whr.CreateGame(players["TkMoreira"], players["Gold Nobody"], WHResult.Player2Win, 3); whr.CreateGame(players["TkMoreira"], players["Gold Nobody"], WHResult.Player1Win, 3); whr.CreateGame(players["TkMoreira"], players["Gold Nobody"], WHResult.Player1Win, 3);         // Strikers In 2019 Group Stage
            whr.CreateGame(players["Christopher"], players["CDH"], WHResult.Player1Win, 3); whr.CreateGame(players["Christopher"], players["CDH"], WHResult.Player1Win, 3); whr.CreateGame(players["Christopher"], players["CDH"], WHResult.Player1Win, 3);         // Strikers In 2019 Group Stage
            whr.CreateGame(players["Christopher"], players["Gold Nobody"], WHResult.Player1Win, 3); whr.CreateGame(players["Christopher"], players["Gold Nobody"], WHResult.Player2Win, 3); whr.CreateGame(players["Christopher"], players["Gold Nobody"], WHResult.Player1Win, 3); whr.CreateGame(players["Christopher"], players["Gold Nobody"], WHResult.Player2Win, 3); whr.CreateGame(players["Christopher"], players["Gold Nobody"], WHResult.Player1Win, 3);         // Strikers In 2019 Group Stage
            whr.CreateGame(players["TkMoreira"], players["CDH"], WHResult.Player1Win, 3); whr.CreateGame(players["TkMoreira"], players["CDH"], WHResult.Player1Win, 3); whr.CreateGame(players["TkMoreira"], players["CDH"], WHResult.Player1Win, 3);           // Strikers In 2019 Group Stage
            whr.CreateGame(players["CDH"], players["Gold Nobody"], WHResult.Player1Win, 3); whr.CreateGame(players["CDH"], players["Gold Nobody"], WHResult.Player1Win, 3); whr.CreateGame(players["CDH"], players["Gold Nobody"], WHResult.Player1Win, 3);         // Strikers In 2019 Group Stage
            whr.CreateGame(players["TkMoreira"], players["Christopher"], WHResult.Player1Win, 3); whr.CreateGame(players["TkMoreira"], players["Christopher"], WHResult.Player1Win, 3); whr.CreateGame(players["TkMoreira"], players["Christopher"], WHResult.Player1Win, 3);           // Strikers In 2019 Group Stage
            whr.CreateGame(players["J0k3r"], players["BigRig"], WHResult.Player1Win, 3); whr.CreateGame(players["J0k3r"], players["BigRig"], WHResult.Player2Win, 3); whr.CreateGame(players["J0k3r"], players["BigRig"], WHResult.Player1Win, 3); whr.CreateGame(players["J0k3r"], players["BigRig"], WHResult.Player1Win, 3);         // Strikers In 2019 Group Stage
            whr.CreateGame(players["BKXO"], players["T-boy"], WHResult.Player1Win, 3); whr.CreateGame(players["BKXO"], players["T-boy"], WHResult.Player1Win, 3); whr.CreateGame(players["BKXO"], players["T-boy"], WHResult.Player1Win, 3);            // Strikers In 2019 Group Stage
            whr.CreateGame(players["BigRig"], players["BKXO"], WHResult.Player1Win, 3); whr.CreateGame(players["BigRig"], players["BKXO"], WHResult.Player1Win, 3); whr.CreateGame(players["BigRig"], players["BKXO"], WHResult.Player1Win, 3);         // Strikers In 2019 Group Stage
            whr.CreateGame(players["J0k3r"], players["T-boy"], WHResult.Player1Win, 3); whr.CreateGame(players["J0k3r"], players["T-boy"], WHResult.Player1Win, 3); whr.CreateGame(players["J0k3r"], players["T-boy"], WHResult.Player1Win, 3);         // Strikers In 2019 Group Stage
            whr.CreateGame(players["J0k3r"], players["BKXO"], WHResult.Player1Win, 3); whr.CreateGame(players["J0k3r"], players["BKXO"], WHResult.Player1Win, 3); whr.CreateGame(players["J0k3r"], players["BKXO"], WHResult.Player1Win, 3);            // Strikers In 2019 Group Stage
            whr.CreateGame(players["BigRig"], players["T-boy"], WHResult.Player1Win, 3); whr.CreateGame(players["BigRig"], players["T-boy"], WHResult.Player1Win, 3); whr.CreateGame(players["BigRig"], players["T-boy"], WHResult.Player1Win, 3);          // Strikers In 2019 Group Stage
            whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 4); whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 4); whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 4); whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 4); // Strikers In 2019 Gold Winners Semi-Final
            whr.CreateGame(players["J0k3r"], players["Christopher"], WHResult.Player1Win, 4); whr.CreateGame(players["J0k3r"], players["Christopher"], WHResult.Player1Win, 4); whr.CreateGame(players["J0k3r"], players["Christopher"], WHResult.Player1Win, 4); whr.CreateGame(players["J0k3r"], players["Christopher"], WHResult.Player1Win, 4); // Strikers In 2019 Gold Winners Semi-Final
            whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 6); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 6); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 6); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 6); // Strikers In 2019 Gold Winners Final
            whr.CreateGame(players["BigRig"], players["Christopher"], WHResult.Player1Win, 6); whr.CreateGame(players["BigRig"], players["Christopher"], WHResult.Player2Win, 6); whr.CreateGame(players["BigRig"], players["Christopher"], WHResult.Player1Win, 6); whr.CreateGame(players["BigRig"], players["Christopher"], WHResult.Player2Win, 6); whr.CreateGame(players["BigRig"], players["Christopher"], WHResult.Player1Win, 6); whr.CreateGame(players["BigRig"], players["Christopher"], WHResult.Player2Win, 6); whr.CreateGame(players["BigRig"], players["Christopher"], WHResult.Player1Win, 6);    // Strikers In 2019 Gold Losers Semi-Final
            whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 8); whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player2Win, 8); whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 8); whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 8); whr.CreateGame(players["TkMoreira"], players["BigRig"], WHResult.Player1Win, 8);    // Strikers In 2019 Gold Losers Final
            whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 10); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player2Win, 10); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 10); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 10); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 10);    // Strikers In 2019 Gold Grand Final
            whr.CreateGame(players["CDH"], players["T-boy"], WHResult.Player1Win, 7); whr.CreateGame(players["CDH"], players["T-boy"], WHResult.Player1Win, 7); whr.CreateGame(players["CDH"], players["T-boy"], WHResult.Player1Win, 7); whr.CreateGame(players["CDH"], players["T-boy"], WHResult.Player1Win, 7); // Strikers In 2019 Silver Semi-Final
            whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player1Win, 9); whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player2Win, 9); whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player1Win, 9); whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player1Win, 9); whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player1Win, 9);    // Strikers In 2019 Silver Final
            whr.CreateGame(players["TkMoreira"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["Rocci"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player1Win, 238);         // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Atto"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["Atto"], players["einBirnenbaum"], WHResult.Player2Win, 238); whr.CreateGame(players["Atto"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["Atto"], players["einBirnenbaum"], WHResult.Player1Win, 238);         // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["TkMoreira"], WHResult.Player1Win, 238); whr.CreateGame(players["BKXO"], players["TkMoreira"], WHResult.Player2Win, 238); whr.CreateGame(players["BKXO"], players["TkMoreira"], WHResult.Player1Win, 238); whr.CreateGame(players["BKXO"], players["TkMoreira"], WHResult.Player2Win, 238); whr.CreateGame(players["BKXO"], players["TkMoreira"], WHResult.Player1Win, 238);            // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["einBirnenbaum"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["einBirnenbaum"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["einBirnenbaum"], players["Rocci"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Giant"], players["Atto"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["Atto"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["Atto"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player2Win, 238); whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player2Win, 238); whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player1Win, 238);            // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Atto"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["Atto"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["Atto"], players["Rocci"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Giant"], players["ImSpiker"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["ImSpiker"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["ImSpiker"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Atto"], players["BKXO"], WHResult.Player1Win, 238); whr.CreateGame(players["Atto"], players["BKXO"], WHResult.Player1Win, 238); whr.CreateGame(players["Atto"], players["BKXO"], WHResult.Player1Win, 238);         // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Giant"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["Rocci"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["einBirnenbaum"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["BKXO"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["BKXO"], players["Rocci"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player2Win, 238); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player1Win, 238);         // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["Atto"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["Atto"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["Atto"], WHResult.Player1Win, 238);         // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["einBirnenbaum"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Giant"], players["BKXO"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["BKXO"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["BKXO"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["Rocci"], WHResult.Player1Win, 238); whr.CreateGame(players["ImSpiker"], players["Rocci"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player1Win, 238); whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Giant"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["einBirnenbaum"], WHResult.Player1Win, 238); whr.CreateGame(players["Giant"], players["einBirnenbaum"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Terrestrial_X"], players["[CELTICS]"], WHResult.Player1Win, 238); whr.CreateGame(players["Terrestrial_X"], players["[CELTICS]"], WHResult.Player1Win, 238); whr.CreateGame(players["Terrestrial_X"], players["[CELTICS]"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["[CELTICS]"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["[CELTICS]"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["[CELTICS]"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["FB-Productions"], WHResult.Player1Win, 238);            // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Yoyo"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["Yoyo"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["Yoyo"], players["FB-Productions"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Terrestrial_X"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["Terrestrial_X"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["Terrestrial_X"], players["FB-Productions"], WHResult.Player1Win, 238);            // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["Yoyo"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["Yoyo"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["Yoyo"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["[CELTICS]"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["[CELTICS]"], players["FB-Productions"], WHResult.Player1Win, 238); whr.CreateGame(players["[CELTICS]"], players["FB-Productions"], WHResult.Player1Win, 238);            // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Terrestrial_X"], players["Yoyo"], WHResult.Player1Win, 238); whr.CreateGame(players["Terrestrial_X"], players["Yoyo"], WHResult.Player1Win, 238); whr.CreateGame(players["Terrestrial_X"], players["Yoyo"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["Yoyo"], players["[CELTICS]"], WHResult.Player1Win, 238); whr.CreateGame(players["Yoyo"], players["[CELTICS]"], WHResult.Player1Win, 238); whr.CreateGame(players["Yoyo"], players["[CELTICS]"], WHResult.Player1Win, 238);          // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["Terrestrial_X"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["Terrestrial_X"], WHResult.Player1Win, 238); whr.CreateGame(players["J0k3r"], players["Terrestrial_X"], WHResult.Player1Win, 238);           // Firestorm Cup '20 Group Stage
            whr.CreateGame(players["FB-Productions"], players["Rocci"], WHResult.Player1Win, 239); whr.CreateGame(players["FB-Productions"], players["Rocci"], WHResult.Player2Win, 239); whr.CreateGame(players["FB-Productions"], players["Rocci"], WHResult.Player1Win, 239); whr.CreateGame(players["FB-Productions"], players["Rocci"], WHResult.Player1Win, 239); whr.CreateGame(players["FB-Productions"], players["Rocci"], WHResult.Player1Win, 239);  // Firestorm Cup '20 Silver Semi-Final
            whr.CreateGame(players["einBirnenbaum"], players["FB-Productions"], WHResult.Player1Win, 240); whr.CreateGame(players["einBirnenbaum"], players["FB-Productions"], WHResult.Player1Win, 240); whr.CreateGame(players["einBirnenbaum"], players["FB-Productions"], WHResult.Player1Win, 240); whr.CreateGame(players["einBirnenbaum"], players["FB-Productions"], WHResult.Player1Win, 240); // Firestorm Cup '20 Silver Final
            whr.CreateGame(players["Giant"], players["[CELTICS]"], WHResult.Player1Win, 241); whr.CreateGame(players["Giant"], players["[CELTICS]"], WHResult.Player1Win, 241); whr.CreateGame(players["Giant"], players["[CELTICS]"], WHResult.Player1Win, 241); whr.CreateGame(players["Giant"], players["[CELTICS]"], WHResult.Player1Win, 241); // Firestorm Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["BKXO"], players["ImSpiker"], WHResult.Player1Win, 241); whr.CreateGame(players["BKXO"], players["ImSpiker"], WHResult.Player2Win, 241); whr.CreateGame(players["BKXO"], players["ImSpiker"], WHResult.Player1Win, 241); whr.CreateGame(players["BKXO"], players["ImSpiker"], WHResult.Player2Win, 241); whr.CreateGame(players["BKXO"], players["ImSpiker"], WHResult.Player1Win, 241); whr.CreateGame(players["BKXO"], players["ImSpiker"], WHResult.Player1Win, 241); // Firestorm Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["J0k3r"], players["Atto"], WHResult.Player1Win, 241); whr.CreateGame(players["J0k3r"], players["Atto"], WHResult.Player1Win, 241); whr.CreateGame(players["J0k3r"], players["Atto"], WHResult.Player1Win, 241); whr.CreateGame(players["J0k3r"], players["Atto"], WHResult.Player1Win, 241); // Firestorm Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["TkMoreira"], players["Yoyo"], WHResult.Player1Win, 241); whr.CreateGame(players["TkMoreira"], players["Yoyo"], WHResult.Player1Win, 241); whr.CreateGame(players["TkMoreira"], players["Yoyo"], WHResult.Player1Win, 241); whr.CreateGame(players["TkMoreira"], players["Yoyo"], WHResult.Player1Win, 241); // Firestorm Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["ImSpiker"], players["[CELTICS]"], WHResult.Player1Win, 242); whr.CreateGame(players["ImSpiker"], players["[CELTICS]"], WHResult.Player1Win, 242); whr.CreateGame(players["ImSpiker"], players["[CELTICS]"], WHResult.Player1Win, 242); whr.CreateGame(players["ImSpiker"], players["[CELTICS]"], WHResult.Player1Win, 242); // Firestorm Cup '20 Gold Losers Round 1
            whr.CreateGame(players["Atto"], players["Yoyo"], WHResult.Player1Win, 242); whr.CreateGame(players["Atto"], players["Yoyo"], WHResult.Player2Win, 242); whr.CreateGame(players["Atto"], players["Yoyo"], WHResult.Player1Win, 242); whr.CreateGame(players["Atto"], players["Yoyo"], WHResult.Player2Win, 242); whr.CreateGame(players["Atto"], players["Yoyo"], WHResult.Player1Win, 242); whr.CreateGame(players["Atto"], players["Yoyo"], WHResult.Player1Win, 242); // Firestorm Cup '20 Gold Losers Round 1
            whr.CreateGame(players["Giant"], players["BKXO"], WHResult.Player1Win, 243); whr.CreateGame(players["Giant"], players["BKXO"], WHResult.Player1Win, 243); whr.CreateGame(players["Giant"], players["BKXO"], WHResult.Player1Win, 243); whr.CreateGame(players["Giant"], players["BKXO"], WHResult.Player1Win, 243); // Firestorm Cup '20 Gold Winners Semi-Final
            whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 243); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 243); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 243); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 243); // Firestorm Cup '20 Gold Winners Semi-Final
            whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 244); whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 244); whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 244); whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 244); // Firestorm Cup '20 Gold Losers Quarter-Final
            whr.CreateGame(players["Atto"], players["BKXO"], WHResult.Player1Win, 244); whr.CreateGame(players["Atto"], players["BKXO"], WHResult.Player1Win, 244); whr.CreateGame(players["Atto"], players["BKXO"], WHResult.Player1Win, 244); whr.CreateGame(players["Atto"], players["BKXO"], WHResult.Player1Win, 244); // Firestorm Cup '20 Gold Losers Quarter-Final
            whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player1Win, 245); whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player2Win, 245); whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player1Win, 245); whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player2Win, 245); whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player1Win, 245); whr.CreateGame(players["TkMoreira"], players["Atto"], WHResult.Player1Win, 245);   // Firestorm Cup '20 Gold Losers Semi-Final
            whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 246); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player2Win, 246); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 246); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player2Win, 246); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 246); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 246); // Firestorm Cup '20 Gold Winners Final
            whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player1Win, 247); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player2Win, 247); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player1Win, 247); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player2Win, 247); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player1Win, 247); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player2Win, 247); whr.CreateGame(players["Giant"], players["TkMoreira"], WHResult.Player1Win, 247);   // Firestorm Cup '20 Gold Losers Final
            whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 248); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 248); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 248); whr.CreateGame(players["J0k3r"], players["Giant"], WHResult.Player1Win, 248); // Firestorm Cup '20 Gold Grand Final
            whr.CreateGame(players["Ajmo1025"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["Luso"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["Jimboom"], WHResult.Player2Win, 315); whr.CreateGame(players["TkMoreira"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["Jimboom"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["sigibua"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Kaz"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["FB-Productions"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["Ajmo1025"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["Ajmo1025"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["Ajmo1025"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Luso"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Kaz"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["Jimboom"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["FB-Productions"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["FB-Productions"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["FB-Productions"], players["sigibua"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["Ajmo1025"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Ajmo1025"], WHResult.Player2Win, 315); whr.CreateGame(players["ImSpiker"], players["Ajmo1025"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Ajmo1025"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Kaz"], players["TkMoreira"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["TkMoreira"], WHResult.Player2Win, 315); whr.CreateGame(players["Kaz"], players["TkMoreira"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["TkMoreira"], WHResult.Player2Win, 315); whr.CreateGame(players["Kaz"], players["TkMoreira"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["FB-Productions"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["FB-Productions"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["FB-Productions"], players["Luso"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["sigibua"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["sigibua"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["sigibua"], players["Jimboom"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Kaz"], players["Ajmo1025"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["Ajmo1025"], WHResult.Player2Win, 315); whr.CreateGame(players["Kaz"], players["Ajmo1025"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["Ajmo1025"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["FB-Productions"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["sigibua"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Luso"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["Luso"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["Luso"], players["Jimboom"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Ajmo1025"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["FB-Productions"], WHResult.Player2Win, 315); whr.CreateGame(players["Ajmo1025"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["FB-Productions"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Jimboom"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["Luso"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Ajmo1025"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["sigibua"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["sigibua"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["FB-Productions"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["FB-Productions"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["FB-Productions"], players["Jimboom"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Kaz"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["Kaz"], players["Luso"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["ImSpiker"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Ajmo1025"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["Jimboom"], WHResult.Player1Win, 315); whr.CreateGame(players["Ajmo1025"], players["Jimboom"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["sigibua"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["sigibua"], players["Luso"], WHResult.Player2Win, 315); whr.CreateGame(players["sigibua"], players["Luso"], WHResult.Player1Win, 315); whr.CreateGame(players["sigibua"], players["Luso"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["TkMoreira"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["FB-Productions"], WHResult.Player1Win, 315); whr.CreateGame(players["TkMoreira"], players["FB-Productions"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["ImSpiker"], players["Kaz"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Kaz"], WHResult.Player1Win, 315); whr.CreateGame(players["ImSpiker"], players["Kaz"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Hi_Am_Disturbia"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Hi_Am_Disturbia"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Hi_Am_Disturbia"], players["DemonMK"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["Calvin"], WHResult.Player2Win, 315); whr.CreateGame(players["BKXO"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["Calvin"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Jucarman"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["Jucarman"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["Jucarman"], players["einBirnenbaum"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Timely Yor"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["CDH"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["DemonMK"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["einBirnenbaum"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["einBirnenbaum"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["einBirnenbaum"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Timely Yor"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["Calvin"], WHResult.Player2Win, 315); whr.CreateGame(players["Timely Yor"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["Calvin"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["CDH"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["Jucarman"], WHResult.Player2Win, 315); whr.CreateGame(players["CDH"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["Jucarman"], WHResult.Player2Win, 315); whr.CreateGame(players["CDH"], players["Jucarman"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["BKXO"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["BKXO"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["BKXO"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["einBirnenbaum"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["einBirnenbaum"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["einBirnenbaum"], players["DemonMK"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["CDH"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Calvin"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["Jucarman"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["einBirnenbaum"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Timely Yor"], players["BKXO"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["BKXO"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["BKXO"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["CDH"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["DemonMK"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Calvin"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["Timely Yor"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Timely Yor"], WHResult.Player2Win, 315); whr.CreateGame(players["J0k3r"], players["Timely Yor"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Timely Yor"], WHResult.Player2Win, 315); whr.CreateGame(players["J0k3r"], players["Timely Yor"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["einBirnenbaum"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["einBirnenbaum"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["einBirnenbaum"], players["CDH"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player2Win, 315); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Calvin"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["DemonMK"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["CDH"], WHResult.Player2Win, 315); whr.CreateGame(players["J0k3r"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["CDH"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Timely Yor"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["Jucarman"], WHResult.Player1Win, 315);           // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Calvin"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["einBirnenbaum"], WHResult.Player2Win, 315); whr.CreateGame(players["Calvin"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["Calvin"], players["einBirnenbaum"], WHResult.Player2Win, 315); whr.CreateGame(players["Calvin"], players["einBirnenbaum"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Jucarman"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Jucarman"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["CDH"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["CDH"], players["Calvin"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Timely Yor"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["Hi_Am_Disturbia"], WHResult.Player2Win, 315); whr.CreateGame(players["Timely Yor"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["DemonMK"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Calvin"], WHResult.Player2Win, 315); whr.CreateGame(players["J0k3r"], players["Calvin"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Calvin"], WHResult.Player2Win, 315); whr.CreateGame(players["J0k3r"], players["Calvin"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Jucarman"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["Jucarman"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["Jucarman"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Timely Yor"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["DemonMK"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["einBirnenbaum"], WHResult.Player1Win, 315);          // Diamond Cup '20 Group Stage
            whr.CreateGame(players["J0k3r"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315); whr.CreateGame(players["J0k3r"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Jucarman"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Jucarman"], players["DemonMK"], WHResult.Player1Win, 315); whr.CreateGame(players["Jucarman"], players["DemonMK"], WHResult.Player1Win, 315);            // Diamond Cup '20 Group Stage
            whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player2Win, 315); whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player1Win, 315); whr.CreateGame(players["BKXO"], players["CDH"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["Timely Yor"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["einBirnenbaum"], WHResult.Player2Win, 315); whr.CreateGame(players["Timely Yor"], players["einBirnenbaum"], WHResult.Player1Win, 315); whr.CreateGame(players["Timely Yor"], players["einBirnenbaum"], WHResult.Player1Win, 315);         // Diamond Cup '20 Group Stage
            whr.CreateGame(players["CDH"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 316); whr.CreateGame(players["CDH"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 316); whr.CreateGame(players["CDH"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 316);           // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["sigibua"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["sigibua"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["sigibua"], players["DemonMK"], WHResult.Player1Win, 316);           // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["FB-Productions"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["FB-Productions"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["FB-Productions"], players["DemonMK"], WHResult.Player1Win, 316);          // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["sigibua"], players["CDH"], WHResult.Player1Win, 316); whr.CreateGame(players["sigibua"], players["CDH"], WHResult.Player2Win, 316); whr.CreateGame(players["sigibua"], players["CDH"], WHResult.Player1Win, 316); whr.CreateGame(players["sigibua"], players["CDH"], WHResult.Player1Win, 316);         // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["Hi_Am_Disturbia"], players["FB-Productions"], WHResult.Player1Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["FB-Productions"], WHResult.Player2Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["FB-Productions"], WHResult.Player1Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["FB-Productions"], WHResult.Player2Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["FB-Productions"], WHResult.Player1Win, 316);            // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["CDH"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["CDH"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["CDH"], players["DemonMK"], WHResult.Player1Win, 316);           // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["FB-Productions"], players["CDH"], WHResult.Player1Win, 316); whr.CreateGame(players["FB-Productions"], players["CDH"], WHResult.Player2Win, 316); whr.CreateGame(players["FB-Productions"], players["CDH"], WHResult.Player1Win, 316); whr.CreateGame(players["FB-Productions"], players["CDH"], WHResult.Player2Win, 316); whr.CreateGame(players["FB-Productions"], players["CDH"], WHResult.Player1Win, 316);            // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["Hi_Am_Disturbia"], players["sigibua"], WHResult.Player1Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["sigibua"], WHResult.Player2Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["sigibua"], WHResult.Player1Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["sigibua"], WHResult.Player2Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["sigibua"], WHResult.Player1Win, 316);           // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["sigibua"], players["FB-Productions"], WHResult.Player1Win, 316); whr.CreateGame(players["sigibua"], players["FB-Productions"], WHResult.Player2Win, 316); whr.CreateGame(players["sigibua"], players["FB-Productions"], WHResult.Player1Win, 316); whr.CreateGame(players["sigibua"], players["FB-Productions"], WHResult.Player1Win, 316);         // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["Hi_Am_Disturbia"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["DemonMK"], WHResult.Player1Win, 316); whr.CreateGame(players["Hi_Am_Disturbia"], players["DemonMK"], WHResult.Player1Win, 316);           // Diamond Cup '20 Redemption Pool 1
            whr.CreateGame(players["Jucarman"], players["Jimboom"], WHResult.Player1Win, 316); whr.CreateGame(players["Jucarman"], players["Jimboom"], WHResult.Player1Win, 316); whr.CreateGame(players["Jucarman"], players["Jimboom"], WHResult.Player1Win, 316);            // Diamond Cup '20 Redemption Pool 2
            whr.CreateGame(players["einBirnenbaum"], players["Luso"], WHResult.Player1Win, 316); whr.CreateGame(players["einBirnenbaum"], players["Luso"], WHResult.Player1Win, 316); whr.CreateGame(players["einBirnenbaum"], players["Luso"], WHResult.Player1Win, 316);          // Diamond Cup '20 Redemption Pool 2
            whr.CreateGame(players["Jucarman"], players["Luso"], WHResult.Player1Win, 316); whr.CreateGame(players["Jucarman"], players["Luso"], WHResult.Player1Win, 316); whr.CreateGame(players["Jucarman"], players["Luso"], WHResult.Player1Win, 316);         // Diamond Cup '20 Redemption Pool 2
            whr.CreateGame(players["einBirnenbaum"], players["Jimboom"], WHResult.Player1Win, 316); whr.CreateGame(players["einBirnenbaum"], players["Jimboom"], WHResult.Player1Win, 316); whr.CreateGame(players["einBirnenbaum"], players["Jimboom"], WHResult.Player1Win, 316);         // Diamond Cup '20 Redemption Pool 2
            whr.CreateGame(players["Jucarman"], players["einBirnenbaum"], WHResult.Player1Win, 316); whr.CreateGame(players["Jucarman"], players["einBirnenbaum"], WHResult.Player2Win, 316); whr.CreateGame(players["Jucarman"], players["einBirnenbaum"], WHResult.Player1Win, 316); whr.CreateGame(players["Jucarman"], players["einBirnenbaum"], WHResult.Player1Win, 316);         // Diamond Cup '20 Redemption Pool 2
            whr.CreateGame(players["Luso"], players["Jimboom"], WHResult.Player1Win, 316); whr.CreateGame(players["Luso"], players["Jimboom"], WHResult.Player1Win, 316); whr.CreateGame(players["Luso"], players["Jimboom"], WHResult.Player1Win, 316);            // Diamond Cup '20 Redemption Pool 2
            whr.CreateGame(players["Luso"], players["FB-Productions"], WHResult.Player1Win, 319); whr.CreateGame(players["Luso"], players["FB-Productions"], WHResult.Player2Win, 319); whr.CreateGame(players["Luso"], players["FB-Productions"], WHResult.Player1Win, 319); whr.CreateGame(players["Luso"], players["FB-Productions"], WHResult.Player1Win, 319); whr.CreateGame(players["Luso"], players["FB-Productions"], WHResult.Player1Win, 319);   // Diamond Cup '20 Silver Semi-Final
            whr.CreateGame(players["CDH"], players["Luso"], WHResult.Player1Win, 320); whr.CreateGame(players["CDH"], players["Luso"], WHResult.Player2Win, 320); whr.CreateGame(players["CDH"], players["Luso"], WHResult.Player1Win, 320); whr.CreateGame(players["CDH"], players["Luso"], WHResult.Player1Win, 320); whr.CreateGame(players["CDH"], players["Luso"], WHResult.Player1Win, 320);  // Diamond Cup '20 Silver Final
            whr.CreateGame(players["J0k3r"], players["Ajmo1025"], WHResult.Player1Win, 316); whr.CreateGame(players["J0k3r"], players["Ajmo1025"], WHResult.Player1Win, 316); whr.CreateGame(players["J0k3r"], players["Ajmo1025"], WHResult.Player1Win, 316); whr.CreateGame(players["J0k3r"], players["Ajmo1025"], WHResult.Player1Win, 316); // Diamond Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player1Win, 316); whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player2Win, 316); whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player1Win, 316); whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player1Win, 316); whr.CreateGame(players["ImSpiker"], players["BKXO"], WHResult.Player1Win, 316); // Diamond Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["TkMoreira"], players["Calvin"], WHResult.Player1Win, 316); whr.CreateGame(players["TkMoreira"], players["Calvin"], WHResult.Player2Win, 316); whr.CreateGame(players["TkMoreira"], players["Calvin"], WHResult.Player1Win, 316); whr.CreateGame(players["TkMoreira"], players["Calvin"], WHResult.Player2Win, 316); whr.CreateGame(players["TkMoreira"], players["Calvin"], WHResult.Player1Win, 316); whr.CreateGame(players["TkMoreira"], players["Calvin"], WHResult.Player1Win, 316);   // Diamond Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["Timely Yor"], players["Kaz"], WHResult.Player1Win, 316); whr.CreateGame(players["Timely Yor"], players["Kaz"], WHResult.Player2Win, 316); whr.CreateGame(players["Timely Yor"], players["Kaz"], WHResult.Player1Win, 316); whr.CreateGame(players["Timely Yor"], players["Kaz"], WHResult.Player2Win, 316); whr.CreateGame(players["Timely Yor"], players["Kaz"], WHResult.Player1Win, 316); whr.CreateGame(players["Timely Yor"], players["Kaz"], WHResult.Player2Win, 316); whr.CreateGame(players["Timely Yor"], players["Kaz"], WHResult.Player1Win, 316);  // Diamond Cup '20 Gold Winners Quarter-Final
            whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player1Win, 317); whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player2Win, 317); whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player1Win, 317); whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player1Win, 317); whr.CreateGame(players["Kaz"], players["sigibua"], WHResult.Player1Win, 317);   // Diamond Cup '20 Gold Losers Round 1
            whr.CreateGame(players["einBirnenbaum"], players["Calvin"], WHResult.Player1Win, 317); whr.CreateGame(players["einBirnenbaum"], players["Calvin"], WHResult.Player2Win, 317); whr.CreateGame(players["einBirnenbaum"], players["Calvin"], WHResult.Player1Win, 317); whr.CreateGame(players["einBirnenbaum"], players["Calvin"], WHResult.Player1Win, 317); whr.CreateGame(players["einBirnenbaum"], players["Calvin"], WHResult.Player1Win, 317);  // Diamond Cup '20 Gold Losers Round 1
            whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player1Win, 317); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player2Win, 317); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player1Win, 317); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player2Win, 317); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player1Win, 317); whr.CreateGame(players["BKXO"], players["Jucarman"], WHResult.Player1Win, 317); // Diamond Cup '20 Gold Losers Round 1
            whr.CreateGame(players["Ajmo1025"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 317); whr.CreateGame(players["Ajmo1025"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 317); whr.CreateGame(players["Ajmo1025"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 317); whr.CreateGame(players["Ajmo1025"], players["Hi_Am_Disturbia"], WHResult.Player1Win, 317); // Diamond Cup '20 Gold Losers Round 1
            whr.CreateGame(players["Kaz"], players["einBirnenbaum"], WHResult.Player1Win, 318); whr.CreateGame(players["Kaz"], players["einBirnenbaum"], WHResult.Player2Win, 318); whr.CreateGame(players["Kaz"], players["einBirnenbaum"], WHResult.Player1Win, 318); whr.CreateGame(players["Kaz"], players["einBirnenbaum"], WHResult.Player1Win, 318); whr.CreateGame(players["Kaz"], players["einBirnenbaum"], WHResult.Player1Win, 318); // Diamond Cup '20 Gold Losers Round 2
            whr.CreateGame(players["BKXO"], players["Ajmo1025"], WHResult.Player1Win, 318); whr.CreateGame(players["BKXO"], players["Ajmo1025"], WHResult.Player2Win, 318); whr.CreateGame(players["BKXO"], players["Ajmo1025"], WHResult.Player1Win, 318); whr.CreateGame(players["BKXO"], players["Ajmo1025"], WHResult.Player2Win, 318); whr.CreateGame(players["BKXO"], players["Ajmo1025"], WHResult.Player1Win, 318); whr.CreateGame(players["BKXO"], players["Ajmo1025"], WHResult.Player2Win, 318); whr.CreateGame(players["BKXO"], players["Ajmo1025"], WHResult.Player1Win, 318); // Diamond Cup '20 Gold Losers Round 2
            whr.CreateGame(players["J0k3r"], players["ImSpiker"], WHResult.Player1Win, 321); whr.CreateGame(players["J0k3r"], players["ImSpiker"], WHResult.Player1Win, 321); whr.CreateGame(players["J0k3r"], players["ImSpiker"], WHResult.Player1Win, 321); whr.CreateGame(players["J0k3r"], players["ImSpiker"], WHResult.Player1Win, 321); // Diamond Cup '20 Gold Winners Semi-Final
            whr.CreateGame(players["Timely Yor"], players["TkMoreira"], WHResult.Player1Win, 321); whr.CreateGame(players["Timely Yor"], players["TkMoreira"], WHResult.Player2Win, 321); whr.CreateGame(players["Timely Yor"], players["TkMoreira"], WHResult.Player1Win, 321); whr.CreateGame(players["Timely Yor"], players["TkMoreira"], WHResult.Player1Win, 321); whr.CreateGame(players["Timely Yor"], players["TkMoreira"], WHResult.Player1Win, 321);  // Diamond Cup '20 Gold Winners Semi-Final
            whr.CreateGame(players["Kaz"], players["ImSpiker"], WHResult.Player1Win, 322); whr.CreateGame(players["Kaz"], players["ImSpiker"], WHResult.Player2Win, 322); whr.CreateGame(players["Kaz"], players["ImSpiker"], WHResult.Player1Win, 322); whr.CreateGame(players["Kaz"], players["ImSpiker"], WHResult.Player1Win, 322); whr.CreateGame(players["Kaz"], players["ImSpiker"], WHResult.Player1Win, 322);  // Diamond Cup '20 Gold Losers Quarter-Final
            whr.CreateGame(players["TkMoreira"], players["BKXO"], WHResult.Player1Win, 322); whr.CreateGame(players["TkMoreira"], players["BKXO"], WHResult.Player1Win, 322); whr.CreateGame(players["TkMoreira"], players["BKXO"], WHResult.Player1Win, 322); whr.CreateGame(players["TkMoreira"], players["BKXO"], WHResult.Player1Win, 322); // Diamond Cup '20 Gold Losers Quarter-Final
            whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 332); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 332); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 332); whr.CreateGame(players["J0k3r"], players["TkMoreira"], WHResult.Player1Win, 332);	// Diamond Cup '20 Gold Grand Final
            
            whr.Iterate(200);

            Console.WriteLine("Player,Rating,Rank");
            foreach (KeyValuePair<string, int> player in players.OrderBy(x => -whr.RatingsForPlayer(x.Value).Last()[1]))
            {
                double rating = whr.RatingsForPlayer(player.Value).Last()[1] + 1000;
                Console.WriteLine(player.Key + "," + Math.Round(rating, 0) + "," + GetRankFromRating(rating));
            }
        }

        public static string GetRankFromRating(double rating)
        {
            if (rating > 1500)
                return "Grand Champion";
            else if (rating >= 1395)
                return "Champion III";
            else if (rating >= 1295)
                return "Champion II";
            else if (rating >= 1195)
                return "Champion I";
            else if (rating >= 1094)
                return "Diamond III";
            else if (rating >= 1011)
                return "Diamond II";
            else if (rating >= 934)
                return "Diamond I";
            else if (rating >= 852)
                return "Platinum III";
            else if (rating >= 771)
                return "Platinum II";
            else if (rating >= 693)
                return "Platinum I";
            else if (rating >= 612)
                return "Gold III";
            else if (rating >= 549)
                return "Gold II";
            else if (rating >= 490)
                return "Gold I";
            else if (rating >= 429)
                return "Silver III";
            else if (rating >= 370)
                return "Silver II";
            else if (rating >= 310)
                return "Silver I";
            else if (rating >= 247)
                return "Bronze III";
            else if (rating >= 188)
                return "Bronze II";
            else
                return "Bronze I";
        }
    }
}
